stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:16.16.0
  script:
    - yarn install
    - yarn test

build project:
  stage: build
  image: node:16.16.0
  script:
    - yarn install
    - yarn build

netlify:
  stage: deploy
  image: node:16.16.0
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
  artifacts:
    paths:
      - build/